config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'login#index'

  resources :to_do_lists do
    post :clone, on: :member
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :to_do_list, optional: true
end

app/models/to_do_list.rb
# frozen_string_literal: true

class ToDoList < ApplicationRecord
  CLONE_NAME_FORMAT = '%s (CLONE)'
  private_constant :CLONE_NAME_FORMAT

  belongs_to :user
  has_many :tasks, -> { order(:position) }, dependent: :delete_all

  accepts_nested_attributes_for :tasks, allow_destroy: true

  validates :name, presence: true

  def clone_with_tasks
    attributes = dup.attributes.merge(
      'name' => format(CLONE_NAME_FORMAT, name),
      'tasks' => tasks.map(&:dup)
    )
    self.class.new(attributes)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :to_do_lists

  devise :omniauthable, omniauth_providers: %i[google_oauth2]
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
# frozen_string_literal: true

class LoginController < ApplicationController
  before_action :redirect_if_already_signed_in

  private

  def redirect_if_already_signed_in
    redirect_to(to_do_lists_path) if user_signed_in?
  end
end

app/controllers/to_do_lists_controller.rb
# frozen_string_literal: true

class ToDoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_to_do_list, except: %i[index new create]
  before_action :render_unauthorized, except: %i[index new create], unless: :current_user_has_permissions?

  def index
    @to_do_lists = current_user.to_do_lists.order(:name)
  end

  def new
    @to_do_list = ToDoList.new
  end

  def create
    @to_do_list = ToDoList.new(to_do_list_params)
    @to_do_list.user = current_user
    if @to_do_list.save
      redirect_to(edit_to_do_list_path(@to_do_list), notice: 'To-do list was successfully created.')
    else
      render(:new)
    end
  end

  def update
    if @to_do_list.update(to_do_list_params)
      redirect_to(edit_to_do_list_path(@to_do_list), notice: 'To-do list was successfully updated.')
    else
      render(:edit)
    end
  end

  def destroy
    @to_do_list.destroy
    redirect_to(to_do_lists_url, notice: 'To-do list was successfully destroyed.')
  end

  def clone
    to_do_list_clone = @to_do_list.clone_with_tasks
    to_do_list_clone.save
    redirect_to(edit_to_do_list_path(to_do_list_clone))
  end

  private

  def set_to_do_list
    @to_do_list = ToDoList.find(params[:id])
  end

  def render_unauthorized
    render(file: 'public/401.html', layout: false, status: :unauthorized)
  end

  def current_user_has_permissions?
    @to_do_list.user == current_user
  end

  def to_do_list_params
    params.require(:to_do_list).permit(:name, tasks_attributes: %i[id content done position _destroy])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      email = email_param
      redirect_to(root_path, alert: 'E-mail not provided by Google. Try again later.') unless email.present?

      user = User.find_or_create_by(email: email)
      sign_in_and_redirect(user, event: :authentication)
    end

    private

    def email_param
      request.env.dig('omniauth.auth', :info, :email)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1"/>

    <%= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': 'reload') %>
    <%= javascript_pack_tag('application', 'data-turbolinks-track': 'reload') %>

    <%= yield(:head) %>
  </head>

  <body class="application">
    <% if user_signed_in? %>
      <header class="application__main-header main-header">
        <h1 class="main-header__title">
          <%=
          link_to(root_path) do
            image_tag(asset_pack_path('media/images/logo.png'), title: 'NList', alt: 'NList logo')
          end
          %>
        </h1>
        <nav>
          <ul class="main-header__list">
            <li class="main-header__list-item">
              <%= link_to('Home', root_path, class: 'main-header__list-item-link') %>
            </li>
            <li class="main-header__list-item">
              <%= link_to('New to-do list', new_to_do_list_path, class: 'main-header__list-item-link') %>
            </li>
            <li class="main-header__list-item">
                <%= link_to('Sign out', destroy_user_session_path, class: 'main-header__list-item-link') %>
            </li>
          </ul>
        </nav>
      </header>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<% content_for(:head) do %>
  <%= javascript_pack_tag('pages/login/index') %>
<% end %>

<div class="login">
  <div class="login__box">
    <%= image_tag(asset_pack_path('media/images/logo.png'), title: 'NList', alt: 'NList logo') %>
    <h1 class="login__title">Sign In to NList</h1>
    <%=
    link_to(
      user_google_oauth2_omniauth_authorize_path,
      method: :post,
      class: 'login__button button button--primary'
    ) do %>
      <%= image_tag(asset_pack_path('media/images/google-icon.png'), alt: 'Google icon', width: '16') %>
      Sign in with Google
    <% end %>
</div>

app/views/to_do_lists/_form.html.erb
<% content_for(:head) do %>
  <%= javascript_pack_tag('pages/to-do-lists/form', 'data-turbolinks-track': 'reload') %>
<% end %>

<div class="form">
  <% if notice.present? %>
    <p class="form__alert alert alert--success"><%= notice %></p>
  <% end %>

  <% if @to_do_list.errors.any? %>
    <p class="form__alert alert alert--error"><%= @to_do_list.errors.full_messages.first %></p>
  <% end %>

  <%= form_with(model: @to_do_list, local: true, class: 'form__to-do-list to-do-list') do |form| %>
    <%= form.text_field(:name, class: 'to-do-list__input', autofocus: true) %>
    <div id="tasks">
      <%= form.fields_for(:tasks) do |task| %>
        <%= render('task_fields', f: task) %>
      <% end %>
    </div>
    <div class="to-do-list__links-wrapper links">
      <%=
      link_to_add_association(
        'New task',
        form,
        :tasks,
        data: {
          association_insertion_method: 'append',
          association_insertion_node: '#tasks'
        },
        class: 'button button--primary to-do-list__link-add-task'
      )
      %>
    </div>
    <%= form.submit('Save', class: 'button button--primary') %>
    <%= link_to('Cancel', to_do_lists_path, class: 'button button--primary') %>
  <% end %>
</div>

app/views/to_do_lists/_task_fields.html.erb
<div class="nested-fields to-do-list__task task">
  <span class="task__drag-icon-wrapper">
    <%= link_to('☰', '#', class: 'task__drag-icon', title: 'Move task') %>
  </span>

  <%= f.check_box(:done, class: 'task__checkbox') %>
  <%= f.text_field(:content, class: "task__input #{f.object.done ? 'task__input-done' : ''}") %>
  <%= f.hidden_field(:position) %>
  <%= link_to_remove_association(f, class: 'action-link') do %>
    <i class="fas fa-trash-alt" title="Remove task"></i>
  <% end %>
</div>

app/views/to_do_lists/edit.html.erb
<%= render('form', to_do_list: @to_do_list) %>

app/views/to_do_lists/index.html.erb
<% content_for(:head) do %>
  <%= javascript_pack_tag('pages/to-do-lists/index') %>
<% end %>

<div class="index">
  <% if notice.present? %>
    <p class="alert alert--success"><%= notice %></p>
  <% end %>

  <% if @to_do_lists.any? %>
    <ul class="index__to-do-list-list">
      <% @to_do_lists.each do |to_do_list| %>
        <li class="index__to-do-list to-do-list to-do-list--compact">
          <%= link_to(to_do_list.name, edit_to_do_list_path(to_do_list), class: 'title-link') %>
          <div>
            <%= link_to(clone_to_do_list_path(to_do_list), method: :post, class: 'action-link') do %>
              <i class="fas fa-clone" title="Clone to-do list"></i>
            <% end %>
            <%= link_to(to_do_list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'action-link') do %>
              <i class="fas fa-trash-alt" title="Remove to-do list"></i>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="alert alert--warning">There are no to-do lists yet.</p>
  <% end %>
</div>

app/views/to_do_lists/new.html.erb
<%= render('form', to_do_list: @to_do_list) %>